openapi: 3.0.0
info:
  title: Payment Service API
servers:
  - url: http://paymentservice.com
paths:
  /payments:
    post:
      summary: Make a new payment.
  /users/{userId}/payments:
    get:
      summary: Return the payments made by user of id {userId}.
